name: Release Build

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Decode Keystore
      run: echo ${{ secrets.KEYSTORE_BASE64 }} | base64 --decode > keystore.jks

    - name: Create keystore.properties
      run: |
        echo "storePassword=$STORE_PASSWORD" > keystore.properties
        echo "keyPassword=$KEY_PASSWORD" >> keystore.properties
        echo "keyAlias=$KEY_ALIAS" >> keystore.properties
        echo "storeFile=../keystore.jks" >> keystore.properties

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Release APK
      run: ./gradlew assembleRelease

    - name: Verify Release APK
      run: |
        if [ ! -f app/build/outputs/apk/release/app-release.apk ]; then
          echo "Release APK not found!"
          exit 1
        fi

    - name: Upload Release APK to GitHub
      uses: softprops/action-gh-release@v1
      with:
        files: app/build/outputs/apk/release/app-release.apk
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: app/build/outputs/apk/release/app-release.apk

    - name: Upload build mapping
      uses: actions/upload-artifact@v4
      with:
        name: mapping
        path: app/build/outputs/mapping/release/

    - name: Cleanup Keystore
      if: always()
      run: rm -f keystore.jks keystore.properties
